name: test and deploy
on:
  push:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          run: |
            docker compose up -d --build
            docker wait test_client
            log_test=$(docker logs test_client)
            if [[ "$log_test" == *"1"* ]]; then
              echo "error"
              docker compose down -v
              exit 1
            elif [[ "$log_test" == *"0"* ]]; then
              echo "success"
              docker compose down -v
              exit 0
            else 
              echo "error no no none"
              docker compose down -v
              exit 1
            fi