name: test and deploy
on:
  push:
    branches:
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          run: |
            docker compose up -d --build
            docker wait test_client
            log_test=$(docker logs test_client)
            if [[ "$log_test" == *"1"* ]]; then
              echo "error"
              docker compose down -v
              exit 1
            elif [[ "$log_test" == *"0"* ]]; then
              echo "success"
              docker compose down -v
              exit 0
            else 
              echo "error no no none"
              docker compose down -v
              exit 1
            fi


    build_and_deploy:
        needs: test
        runs-on: ubuntu-latest
        if: success()
        steps:
          - uses: actions/checkout@v3
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build and push Docker image
            run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:latest .
              docker push ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:latest
              echo "✅ האימג' הועלה ל-Docker Hub!"